### ISSUE TITLE
Missing instruction: how to start your app

### ISSUE THREAD

**Issue by greenrd** [bowler-framework/bowler-quickstart#2]
Neither in the README of this project, nor in the Bowler docs, can I find any information on how to start a Bowler app.

In https://github.com/wfaler/Bowler/tree/master/examples it does say "jetty-run from within sbt will start your webapp at http://localhost:8080", but this doesn't work for me with xsbt-web-plugin 0.2.11. sbt says:

[error] Not a valid command: jetty-run

**Comment by greenrd** [comment]
OK, I found the instructions [here](https://github.com/siasia/xsbt-web-plugin/wiki/).

**Comment by wfaler** [comment]
readme probably wasnt updated with the move to sbt 0.11 for the quickstart, think it is "container:start" as off sbt 0.11.x. readme needs updating.
